import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { NextRequest } from 'next/server';
import sharp from 'sharp';

// Rate limiting is stubbed so repeated same-IP requests in this file never 429.
vi.mock('@/lib/middleware/rate-limiter', () => ({
  createRateLimiter: vi.fn(() => vi.fn(async () => null)),
  rateLimitConfigs: {
    gemini: {
      models: { requests: 30, windowMs: 60000 },
      analyze: { requests: 10, windowMs: 60000 },
    },
    nanobanana: {
      generate: { requests: 5, windowMs: 60000 },
      status: { requests: 60, windowMs: 60000 },
      batch: { requests: 2, windowMs: 60000 },
    },
  },
}));

// The Pollinations client is mocked; the normalizer + image store run for real,
// so mocked results must carry real, sharp-decodable image bytes.
vi.mock('@/lib/nanobanana', () => ({
  createNanoBananaClient: vi.fn(() => ({
    generateImage: vi.fn(),
    getJobStatus: vi.fn(),
    checkVersion: vi.fn(),
  })),
  NanoBananaError: class NanoBananaError extends Error {
    constructor(
      message: string,
      public statusCode?: number
    ) {
      super(message);
      this.name = 'NanoBananaError';
    }
  },
}));

import { imageStore } from '@/lib/image-store';

async function pngBytes(width: number, height: number): Promise<Buffer> {
  return sharp({
    create: { width, height, channels: 3, background: { r: 200, g: 60, b: 90 } },
  })
    .png()
    .toBuffer();
}

function idFromUrl(url: string): string {
  return url.replace('/api/images/', '');
}

describe('Nano Banana API Routes (store-backed)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    imageStore.clear();
    process.env.NANO_BANANA_API_KEY = 'test-api-key';
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('POST /api/nanobanana/generate', () => {
    it('normalizes generated bytes to 1200x1200 and serves them at /api/images/<id>', async () => {
      const mockResult = {
        jobId: 'pollinations-icon-123',
        status: 'completed',
        imageUrl: 'https://image.pollinations.ai/prompt/test',
        width: 1200,
        height: 1200,
        format: 'png',
        buffer: await pngBytes(1024, 1024),
      };

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateImage: vi.fn().mockResolvedValue(mockResult),
      });

      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'icon', prompt: 'A simple app icon for an e-commerce tool' }),
      });

      const response = await POST(request);
      expect(response.status).toBe(200);
      const data = await response.json();

      expect(data.jobId).toBe('pollinations-icon-123');
      expect(data.status).toBe('completed');
      expect(data.image).toBeDefined();
      expect(data.image.url).toMatch(/^\/api\/images\/[0-9a-f-]+$/i);
      expect(data.image.width).toBe(1200);
      expect(data.image.height).toBe(1200);
      expect(data.image.provider).toBe('pollinations');
      expect(Array.isArray(data.warnings)).toBe(true);

      const stored = imageStore.get(idFromUrl(data.image.url));
      expect(stored).toBeDefined();
      const meta = await sharp(stored!.buffer).metadata();
      expect(meta.width).toBe(1200);
      expect(meta.height).toBe(1200);
      expect(meta.format).toBe('png');
    });

    it('normalizes a feature image to 1600x900', async () => {
      const mockResult = {
        jobId: 'pollinations-feature-456',
        status: 'completed',
        imageUrl: 'https://image.pollinations.ai/prompt/feature',
        width: 1600,
        height: 900,
        format: 'png',
        buffer: await pngBytes(1408, 768),
      };

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateImage: vi.fn().mockResolvedValue(mockResult),
      });

      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'feature',
          prompt: 'A feature image showing dashboard',
          featureHighlight: 'Real-time analytics',
        }),
      });

      const response = await POST(request);
      expect(response.status).toBe(200);
      const data = await response.json();
      expect(data.image.width).toBe(1600);
      expect(data.image.height).toBe(900);
      expect(data.image.url).toMatch(/^\/api\/images\//);

      const meta = await sharp(imageStore.get(idFromUrl(data.image.url))!.buffer).metadata();
      expect(meta.width).toBe(1600);
      expect(meta.height).toBe(900);
    });

    it('returns 400 for missing type', async () => {
      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: 'A simple icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(400);
      expect((await response.json()).error).toContain('type');
    });

    it('returns 400 for missing prompt', async () => {
      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(400);
      expect((await response.json()).error).toBeDefined();
    });

    it('returns 400 for invalid image type', async () => {
      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'invalid-type', prompt: 'A simple icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(400);
      expect((await response.json()).error).toContain('type');
    });

    it('maps an upstream NanoBananaError (502) to 502', async () => {
      const { createNanoBananaClient, NanoBananaError } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateImage: vi.fn().mockRejectedValue(new NanoBananaError('upstream failed', 502)),
      });

      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'icon', prompt: 'A simple icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(502);
    });
  });

  describe('GET /api/nanobanana/status/[jobId]', () => {
    it('should return job status', async () => {
      const mockStatus = {
        jobId: 'job-123',
        status: 'completed',
        progress: 100,
      };

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        getJobStatus: vi.fn().mockResolvedValue(mockStatus),
      });

      const { GET } = await import('@/app/api/nanobanana/status/[jobId]/route');
      const request = new NextRequest('http://localhost/api/nanobanana/status/job-123');
      const response = await GET(request, { params: Promise.resolve({ jobId: 'job-123' }) });

      expect(response.status).toBe(200);
      const data = await response.json();
      expect(data.jobId).toBe('job-123');
      expect(data.status).toBe('completed');
    });

    it('should return processing status for incomplete jobs', async () => {
      const mockStatus = {
        jobId: 'job-789',
        status: 'processing',
        progress: 50,
      };

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        getJobStatus: vi.fn().mockResolvedValue(mockStatus),
      });

      const { GET } = await import('@/app/api/nanobanana/status/[jobId]/route');
      const request = new NextRequest('http://localhost/api/nanobanana/status/job-789');
      const response = await GET(request, { params: Promise.resolve({ jobId: 'job-789' }) });

      expect(response.status).toBe(200);
      const data = await response.json();
      expect(data.status).toBe('processing');
      expect(data.progress).toBe(50);
    });

    it('should return 404 for non-existent job', async () => {
      const { createNanoBananaClient, NanoBananaError } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        getJobStatus: vi.fn().mockRejectedValue(new NanoBananaError('Job not found', 404)),
      });

      const { GET } = await import('@/app/api/nanobanana/status/[jobId]/route');
      const request = new NextRequest('http://localhost/api/nanobanana/status/invalid-job');
      const response = await GET(request, { params: Promise.resolve({ jobId: 'invalid-job' }) });

      expect(response.status).toBe(404);
    });
  });
});
