import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { NextRequest } from 'next/server';
import sharp from 'sharp';

// Rate limiting is stubbed so repeated same-IP requests in this file never 429.
vi.mock('@/lib/middleware/rate-limiter', () => ({
  createRateLimiter: vi.fn(() => vi.fn(async () => null)),
  rateLimitConfigs: {
    gemini: {
      models: { requests: 30, windowMs: 60000 },
      analyze: { requests: 10, windowMs: 60000 },
    },
    nanobanana: {
      generate: { requests: 5, windowMs: 60000 },
      status: { requests: 60, windowMs: 60000 },
      batch: { requests: 2, windowMs: 60000 },
    },
  },
}));

// The Pollinations client is mocked; the normalizer + image store run for real,
// so mocked results must carry real, sharp-decodable image bytes.
vi.mock('@/lib/nanobanana', () => ({
  createNanoBananaClient: vi.fn(() => ({
    generateImage: vi.fn(),
  })),
  NanoBananaError: class NanoBananaError extends Error {
    constructor(
      message: string,
      public statusCode?: number
    ) {
      super(message);
      this.name = 'NanoBananaError';
    }
  },
}));

// Batch route dependencies: DB + generated-image persistence are mocked;
// prompt-generator runs for real so the featureList wiring is verified
// end-to-end rather than against a mock.
const findOneMock = vi.fn();
const updateOneMock = vi.fn().mockResolvedValue({ acknowledged: true });
vi.mock('@/lib/mongodb', () => ({
  getDatabaseConnected: vi.fn(async () => ({
    collection: vi.fn(() => ({
      findOne: findOneMock,
      updateOne: updateOneMock,
    })),
  })),
}));

vi.mock('@/lib/db/images', () => ({
  createGeneratedImage: vi.fn(async (_db, input) => ({ _id: 'mock-image-id', ...input })),
}));

import { imageStore } from '@/lib/image-store';

async function pngBytes(width: number, height: number): Promise<Buffer> {
  return sharp({
    create: { width, height, channels: 3, background: { r: 200, g: 60, b: 90 } },
  })
    .png()
    .toBuffer();
}

function idFromUrl(url: string): string {
  return url.replace('/api/images/', '');
}

describe('Nano Banana API Routes (store-backed)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    imageStore.clear();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('POST /api/nanobanana/generate', () => {
    it('normalizes generated bytes to 1200x1200 and serves them at /api/images/<id>', async () => {
      const mockResult = {
        jobId: 'pollinations-icon-123',
        status: 'completed',
        imageUrl: 'https://image.pollinations.ai/prompt/test',
        width: 1200,
        height: 1200,
        format: 'png',
        buffer: await pngBytes(1024, 1024),
      };

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateImage: vi.fn().mockResolvedValue(mockResult),
      });

      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'icon', prompt: 'A simple app icon for an e-commerce tool' }),
      });

      const response = await POST(request);
      expect(response.status).toBe(200);
      const data = await response.json();

      expect(data.jobId).toBe('pollinations-icon-123');
      expect(data.status).toBe('completed');
      expect(data.image).toBeDefined();
      expect(data.image.url).toMatch(/^\/api\/images\/[0-9a-f-]+$/i);
      expect(data.image.width).toBe(1200);
      expect(data.image.height).toBe(1200);
      expect(data.image.provider).toBe('pollinations');
      expect(Array.isArray(data.warnings)).toBe(true);

      const stored = imageStore.get(idFromUrl(data.image.url));
      expect(stored).toBeDefined();
      const meta = await sharp(stored!.buffer).metadata();
      expect(meta.width).toBe(1200);
      expect(meta.height).toBe(1200);
      expect(meta.format).toBe('png');
    });

    it('normalizes a feature image to 1600x900', async () => {
      const mockResult = {
        jobId: 'pollinations-feature-456',
        status: 'completed',
        imageUrl: 'https://image.pollinations.ai/prompt/feature',
        width: 1600,
        height: 900,
        format: 'png',
        buffer: await pngBytes(1408, 768),
      };

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateImage: vi.fn().mockResolvedValue(mockResult),
      });

      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'feature',
          prompt: 'A feature image showing dashboard',
          featureHighlight: 'Real-time analytics',
        }),
      });

      const response = await POST(request);
      expect(response.status).toBe(200);
      const data = await response.json();
      expect(data.image.width).toBe(1600);
      expect(data.image.height).toBe(900);
      expect(data.image.url).toMatch(/^\/api\/images\//);

      const meta = await sharp(imageStore.get(idFromUrl(data.image.url))!.buffer).metadata();
      expect(meta.width).toBe(1600);
      expect(meta.height).toBe(900);
    });

    it('returns 400 for missing type', async () => {
      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: 'A simple icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(400);
      expect((await response.json()).error).toContain('type');
    });

    it('returns 400 for missing prompt', async () => {
      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(400);
      expect((await response.json()).error).toBeDefined();
    });

    it('returns 400 for invalid image type', async () => {
      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'invalid-type', prompt: 'A simple icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(400);
      expect((await response.json()).error).toContain('type');
    });

    it('maps an upstream NanoBananaError (502) to 502', async () => {
      const { createNanoBananaClient, NanoBananaError } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateImage: vi.fn().mockRejectedValue(new NanoBananaError('upstream failed', 502)),
      });

      const { POST } = await import('@/app/api/nanobanana/generate/route');
      const request = new NextRequest('http://localhost/api/nanobanana/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: 'icon', prompt: 'A simple icon' }),
      });
      const response = await POST(request);
      expect(response.status).toBe(502);
    });
  });

  describe('POST /api/nanobanana/batch', () => {
    it('reads submission.featureList (not the removed features field) for batch prompts', async () => {
      const submissionId = '507f1f77bcf86cd799439011';
      findOneMock.mockResolvedValue({
        _id: submissionId,
        appName: 'Test App',
        appDescription: 'A helpful test app',
        primaryCategory: 'Sales and conversion',
        featureList: ['Live inventory sync', 'One-click reorder'],
        status: 'draft',
      });

      const { createNanoBananaClient } = await import('@/lib/nanobanana');
      (createNanoBananaClient as ReturnType<typeof vi.fn>).mockReturnValue({
        generateBatch: vi
          .fn()
          .mockImplementation(async (requests: Array<{ type: 'icon' | 'feature' }>) =>
            requests.map((req, i) => ({
              jobId: `batch-job-${i}`,
              status: 'completed' as const,
              imageUrl: `https://image.pollinations.ai/prompt/mock-${i}`,
              width: req.type === 'icon' ? 1200 : 1600,
              height: req.type === 'icon' ? 1200 : 900,
              format: 'png' as const,
            }))
          ),
      });

      const { POST } = await import('@/app/api/nanobanana/batch/route');
      const request = new NextRequest('http://localhost/api/nanobanana/batch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ submissionId }),
      });

      const response = await POST(request);
      expect(response.status).toBe(200);
      const data = await response.json();

      // Regression guard for the migration-debris bug (spec item #5): the
      // batch route used to read `submission.features`, a field the DB
      // never writes (it stores `featureList`), so no feature prompt ever
      // carried the submission's real feature text. With the fix, the
      // submission's own features flow through into the generated prompts.
      const highlighted = data.images.map(
        (img: { featureHighlighted?: string }) => img.featureHighlighted
      );
      expect(highlighted).toContain('Live inventory sync');
      expect(highlighted).toContain('One-click reorder');
    });
  });
});
